# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types:
      - published

jobs:
  format:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install NodeJS
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run format
        run: npm run lint

  deploy:
    if: ${{ github.event_name == 'release' }}
    needs: format
    runs-on: ubuntu-24.04

    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install NodeJS
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: packages
          path: |
            dist
            package.json

      - name: Dispatch deployment
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
        run: >
          gh workflow run deploy-passwordless-nodejs
          --repo bitwarden/passwordless-devops
          --field repository=${{ github.repository }}
          --field run-id=${{ github.run_id }}
          --field artifact=packages
          --field environment=npm
          --field version=${{ github.event.release.tag_name }}
